### ISSUE TITLE
Looking forward to a container based on PHP 8

### ISSUE THREAD

**Issue by discovery-ukraine** [spacetab-io/docker-amphp-php#1]
When are you planning to build a PHP 8 based container?
Thanks a lot for your work!

**Comment by roquie** [comment]
Yeah, I am forgot about it. Until end of this week it will done.

**Comment by discovery-ukraine** [comment]
Thanks for the answer! I will wait very much)

**Comment by discovery-ukraine** [comment]
Still waiting :)

**Comment by discovery-ukraine** [comment]
Closed after a long period of time with no response
